version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: sphere_lead_db
      POSTGRES_USER: lead_user
      POSTGRES_PASSWORD: lead_password
    ports:
      - "9012:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  lead-service:
    build:
      context: ./lead-service
      dockerfile: Dockerfile
    container_name: lead-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: lead_user
      DB_PASSWORD: lead_password
      DB_NAME: sphere_lead_db
    depends_on:
      - postgres
    ports:
      - "9014:8080"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9013:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
