server:
  port: 8080

grpc:
  auditing_service:
    address: "localhost:50051"
  business_service:
    address: "localhost:50052"
  lid_service:
    address: "lead-service:8080"  # Updated to point to the lead-service in Docker
  user_service:
    address: "localhost:50054"
