server:
  port: 8080

grpc:
  education_service:
    address: "education-service:80"
  lid_service:
    address: "lead-service:80"
  user_service:
    address: "user-service:80"
  finance_service:
    address: "finance-service:80"

#server:
#  port: 8080
#
#grpc:
#  auditing_service:
#    address: "localhost:50051"
#  education_service:
#    address: "localhost:50052"
#  lid_service:
#    address: "localhost:50053"
#  user_service:
#    address: "localhost:50055"
#  finance_service:
#    address: "localhost:50056"