server:
  port: 50052

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "modme_education_db"
  sslmode: "disable"
  action: "no"


grpc:
  userService:
    address: "localhost:50055"
  financeService:
    address: "localhost:50056"

#server:
#  port: 8080
#
#database:
#  host: "postgres-sphere-education"
#  port: 5432
#  user: "postgres"
#  password: "password"
#  dbname: "sphere_education_db"
#  sslmode: "disable"
#  action: "no"
#
#grpc:
#  userService:
#    address: "sphere-user-service:8080"
#  finance_service:
#    address: "sphere-finance-service:8080"