server:
  port: 80

database:
  host: "education-postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "sphere_education_db"
  sslmode: "disable"
  action: "no"

grpc:
  userService:
    address: "user-service:80"
  financeService:
    address: "finance-service:80"
  leadService:
    address: "lead-service:80"