version: v2
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  auth_token: "737124f0b6c9f4b65a344ca99427f946"
  log:
    output: stderr
    severity: INFO

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: "sphere-cluster"
  tokens:
    - "node:737124f0b6c9f4b65a344ca99427f946"
  public_addr: ["127.0.0.1:3025"]

ssh_service:
  enabled: "yes"
  labels:
    environment: "production"

proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  public_addr: ["127.0.0.1"]
  https_keypairs: []
  acme:
    enabled: "no"