// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: education.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CourseId        int32                  `protobuf:"varint,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	TeacherId       string                 `protobuf:"bytes,3,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Days            []string               `protobuf:"bytes,5,rep,name=days,proto3" json:"days,omitempty"`
	RoomId          int32                  `protobuf:"varint,6,opt,name=roomId,proto3" json:"roomId,omitempty"`
	LessonStartTime string                 `protobuf:"bytes,7,opt,name=lessonStartTime,proto3" json:"lessonStartTime,omitempty"`
	GroupStartDate  string                 `protobuf:"bytes,8,opt,name=groupStartDate,proto3" json:"groupStartDate,omitempty"`
	GroupEndDate    string                 `protobuf:"bytes,9,opt,name=groupEndDate,proto3" json:"groupEndDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_education_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CreateGroupRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CreateGroupRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateGroupRequest) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *CreateGroupRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateGroupRequest) GetLessonStartTime() string {
	if x != nil {
		return x.LessonStartTime
	}
	return ""
}

func (x *CreateGroupRequest) GetGroupStartDate() string {
	if x != nil {
		return x.GroupStartDate
	}
	return ""
}

func (x *CreateGroupRequest) GetGroupEndDate() string {
	if x != nil {
		return x.GroupEndDate
	}
	return ""
}

type CreateStudentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber       string                 `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth       string                 `protobuf:"bytes,3,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	Gender            bool                   `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	AdditionalContact string                 `protobuf:"bytes,5,opt,name=additionalContact,proto3" json:"additionalContact,omitempty"`
	Address           string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	PassportId        string                 `protobuf:"bytes,7,opt,name=passportId,proto3" json:"passportId,omitempty"`
	TelegramUsername  string                 `protobuf:"bytes,10,opt,name=telegramUsername,proto3" json:"telegramUsername,omitempty"`
	GroupId           string                 `protobuf:"bytes,8,opt,name=groupId,proto3" json:"groupId,omitempty"`
	DateFrom          string                 `protobuf:"bytes,9,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	CreatedBy         string                 `protobuf:"bytes,11,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_education_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStudentRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStudentRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateStudentRequest) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *CreateStudentRequest) GetAdditionalContact() string {
	if x != nil {
		return x.AdditionalContact
	}
	return ""
}

func (x *CreateStudentRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateStudentRequest) GetPassportId() string {
	if x != nil {
		return x.PassportId
	}
	return ""
}

func (x *CreateStudentRequest) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

func (x *CreateStudentRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateStudentRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *CreateStudentRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetCourseByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseByIdRequest) Reset() {
	*x = GetCourseByIdRequest{}
	mi := &file_education_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByIdRequest) ProtoMessage() {}

func (x *GetCourseByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCourseByIdRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{2}
}

func (x *GetCourseByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCourseByIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LessonDuration int32                  `protobuf:"varint,2,opt,name=lessonDuration,proto3" json:"lessonDuration,omitempty"`
	CourseDuration int32                  `protobuf:"varint,3,opt,name=courseDuration,proto3" json:"courseDuration,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	StudentCount   int32                  `protobuf:"varint,6,opt,name=studentCount,proto3" json:"studentCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCourseByIdResponse) Reset() {
	*x = GetCourseByIdResponse{}
	mi := &file_education_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByIdResponse) ProtoMessage() {}

func (x *GetCourseByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCourseByIdResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCourseByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCourseByIdResponse) GetLessonDuration() int32 {
	if x != nil {
		return x.LessonDuration
	}
	return 0
}

func (x *GetCourseByIdResponse) GetCourseDuration() int32 {
	if x != nil {
		return x.CourseDuration
	}
	return 0
}

func (x *GetCourseByIdResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetCourseByIdResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetCourseByIdResponse) GetStudentCount() int32 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

var File_education_proto protoreflect.FileDescriptor

const file_education_proto_rawDesc = "" +
	"\n" +
	"\x0feducation.proto\x12\teducation\x1a\fcommon.proto\"\x98\x02\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcourseId\x18\x02 \x01(\x05R\bcourseId\x12\x1c\n" +
	"\tteacherId\x18\x03 \x01(\tR\tteacherId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04days\x18\x05 \x03(\tR\x04days\x12\x16\n" +
	"\x06roomId\x18\x06 \x01(\x05R\x06roomId\x12(\n" +
	"\x0flessonStartTime\x18\a \x01(\tR\x0flessonStartTime\x12&\n" +
	"\x0egroupStartDate\x18\b \x01(\tR\x0egroupStartDate\x12\"\n" +
	"\fgroupEndDate\x18\t \x01(\tR\fgroupEndDate\"\xee\x02\n" +
	"\x14CreateStudentRequest\x12 \n" +
	"\vphoneNumber\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdateOfBirth\x18\x03 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\bR\x06gender\x12,\n" +
	"\x11additionalContact\x18\x05 \x01(\tR\x11additionalContact\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"passportId\x18\a \x01(\tR\n" +
	"passportId\x12*\n" +
	"\x10telegramUsername\x18\n" +
	" \x01(\tR\x10telegramUsername\x12\x18\n" +
	"\agroupId\x18\b \x01(\tR\agroupId\x12\x1a\n" +
	"\bdateFrom\x18\t \x01(\tR\bdateFrom\x12\x1c\n" +
	"\tcreatedBy\x18\v \x01(\tR\tcreatedBy\"&\n" +
	"\x14GetCourseByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe7\x01\n" +
	"\x15GetCourseByIdResponse\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0elessonDuration\x18\x02 \x01(\x05R\x0elessonDuration\x12&\n" +
	"\x0ecourseDuration\x18\x03 \x01(\x05R\x0ecourseDuration\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\fstudentCount\x18\x06 \x01(\x05R\fstudentCount2Q\n" +
	"\fGroupService\x12A\n" +
	"\vCreateGroup\x12\x1d.education.CreateGroupRequest\x1a\x13.common.AbsResponse2W\n" +
	"\x0eStudentService\x12E\n" +
	"\rCreateStudent\x12\x1f.education.CreateStudentRequest\x1a\x13.common.AbsResponse2c\n" +
	"\rCourseService\x12R\n" +
	"\rGetCourseById\x12\x1f.education.GetCourseByIdRequest\x1a .education.GetCourseByIdResponseB\n" +
	"Z\bproto/pbb\x06proto3"

var (
	file_education_proto_rawDescOnce sync.Once
	file_education_proto_rawDescData []byte
)

func file_education_proto_rawDescGZIP() []byte {
	file_education_proto_rawDescOnce.Do(func() {
		file_education_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)))
	})
	return file_education_proto_rawDescData
}

var file_education_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_education_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),    // 0: education.CreateGroupRequest
	(*CreateStudentRequest)(nil),  // 1: education.CreateStudentRequest
	(*GetCourseByIdRequest)(nil),  // 2: education.GetCourseByIdRequest
	(*GetCourseByIdResponse)(nil), // 3: education.GetCourseByIdResponse
	(*AbsResponse)(nil),           // 4: common.AbsResponse
}
var file_education_proto_depIdxs = []int32{
	0, // 0: education.GroupService.CreateGroup:input_type -> education.CreateGroupRequest
	1, // 1: education.StudentService.CreateStudent:input_type -> education.CreateStudentRequest
	2, // 2: education.CourseService.GetCourseById:input_type -> education.GetCourseByIdRequest
	4, // 3: education.GroupService.CreateGroup:output_type -> common.AbsResponse
	4, // 4: education.StudentService.CreateStudent:output_type -> common.AbsResponse
	3, // 5: education.CourseService.GetCourseById:output_type -> education.GetCourseByIdResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_education_proto_init() }
func file_education_proto_init() {
	if File_education_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_education_proto_goTypes,
		DependencyIndexes: file_education_proto_depIdxs,
		MessageInfos:      file_education_proto_msgTypes,
	}.Build()
	File_education_proto = out.File
	file_education_proto_goTypes = nil
	file_education_proto_depIdxs = nil
}
