apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  labels:
    name: api-gateway
spec:
  containers:
    - name: api-gateway
      image: omonov2006/modme-microservices-clone-sphere-api-gateway:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: 250m
          memory: 256Mi
---

apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  labels:
    name: api-gateway
spec:
  containers:
    - name: api-gateway
      image: omonov2006/modme-microservices-clone-sphere-api-gateway:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: 250m
          memory: 256Mi
---

apiVersion: v1
kind: Pod
metadata:
  name: education-service
  labels:
    name: education-service
spec:
  containers:
    - name: education-service
      image: omonov2006/modme-microservices-clone-sphere-education-service:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: 250m
          memory: 256Mi
---

apiVersion: v1
kind: Pod
metadata:
  name: finance-service
  labels:
    name: finance-service
spec:
  containers:
    - name: finance-service
      image: omonov2006/modme-microservices-clone-sphere-finance-service:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: 250m
          memory: 256Mi
---

apiVersion: v1
kind: Pod
metadata:
  name: lead-service
  labels:
    name: lead-service
spec:
  containers:
    - name: lead-service
      image: omonov2006/modme-microservices-clone-sphere-lead-service:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: 250m
          memory: 256Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: user-service
  labels:
    name: user-service
spec:
  containers:
    - name: user-service
      image: omonov2006/modme-microservices-clone-sphere-user-service:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: 250m
          memory: 256Mi