apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configs
data:
  EDUCATION_POSTGRES_DB: "sphere_education_db"
  EDUCATION_POSTGRES_USER: "postgres"
  FINANCE_POSTGRES_DB: "sphere_finance_db"
  FINANCE_POSTGRES_USER: "postgres"
  LEAD_POSTGRES_DB: "sphere_lead_db"
  LEAD_POSTGRES_USER: "postgres"
  USER_POSTGRES_DB: "sphere_user_db"
  USER_POSTGRES_USER: "postgres"