apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    name: api-gateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP



---

apiVersion: v1
kind: Service
metadata:
  name: education-service
spec:
  selector:
    name: education-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    name: finance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: education-service
spec:
  selector:
    name: education-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: lead-service
spec:
  selector:
    name: lead-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: education-service
spec:
  selector:
    name: education-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    name: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
---
apiVersion: v1
kind: Service
metadata:
  name: education-postgres
spec:
  selector:
    name: education-postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: finance-postgres
spec:
  selector:
    name: finance-postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: lead-postgres
spec:
  selector:
    name: lead-postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres
spec:
  selector:
    name: user-postgres
  ports:
    - port: 5432
      targetPort: 5432