apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: modme-microservices-clone-sphere-user-service
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-sphere-user
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: sphere_user_db
