server:
  port: 8080

database:
  host: "finance-postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "sphere_finance_db"
  sslmode: "disable"
  action: "no"

grpc:
  userService:
    address: "user-service:80"
  educationService:
    address: "education-service:80"