server:
  port: 50056

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "modme_finance_db"
  sslmode: "disable"
  action: "up"


grpc:
  userService:
    address: "localhost:50055"
  educationService:
    address: "localhost:50052"