server:
  port: 8080

database:
  host: "postgres"  # Updated to match the Docker service name
  port: 5432
  user: "lead_user"  # Matches the environment variables in Docker Compose
  password: "lead_password"
  dbname: "sphere_lead_db"
  sslmode: "disable"
  action: "up"
