server:
  port: 8080

database:
  host: "lead-postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "sphere_lead_db"
  sslmode: "disable"
  action: "no"

grpc:
  education_service:
    address: "education-service:80"
  user_service:
    address: "user-service:80"