server:
  port: 8080

database:
  host: "postgres"
  port: 5432
  user: "lead_user"
  password: "lead_password"
  dbname: "sphere_lead_db"
  sslmode: "disable"
  action: "no"



#server:
#  port: 50053
#
#database:
#  host: "localhost"
#  port: 5432
#  user: "postgres"
#  password: "postgres"
#  dbname: "modme_lead_db"
#  sslmode: "disable"
#  action: "up"
