#server:
#  port: 8080
#
#database:
#  host: "postgres-sphere-lead"
#  port: 5432
#  user: "postgres"
#  password: "password"
#  dbname: "sphere_lead_db"
#  sslmode: "disable"
#  action: "no"
#
#
#grpc:
#  education_service:
#    address: "sphere-education-service:8080"
#

server:
  port: 50053

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "modme_lead_db"
  sslmode: "disable"
  action: "up"
grpc:
  education_service:
    address: "localhost:50052"
