server:
  port: 50055

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "modme_user_db"
  sslmode: "disable"
  action: "up"

grpc:
  educationService:
    address: "localhost:50052"

#server:
#  port: 8080
#
#database:
#  host: "postgres-sphere-user"
#  port: 5432
#  user: "postgres"
#  password: "password"
#  name: "sphere_user_db"
#  sslmode: "disable"
#  action: "up"
#grpc:
#  educationService:
#    address: "sphere-education-service:8080"
