server:
  port: 50055

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "modme_user_db"
  sslmode: "disable"
  action: "up"

#server:
#  port: 50055
#
#database:
#  host: "postgres-sphere-user"
#  port: 5432
#  user: "postgres"
#  password: "postgres"
#  name: "sphere_user_db"
#  sslmode: "disable"
#  action: "up"
