server:
  port: 8080

database:
  host: "user-postgres"
  port: 5432
  user: "postgres"
  password: "password"
  name: "sphere_user_db"
  sslmode: "disable"
  action: "no"

grpc:
  educationService:
    address: "education-service:80"